export const ALL_TAGS = [
  'Donated 2025',
  'Donated 2026',
  'Past Donor',
  'Lapsed Donor',
  'High-Priority Donor',
  'Small-Dollar Donor',
  'Recurring Donor',
  'Volunteer Signup',
  'Old Volunteer Signup',
  'Active Volunteer',
  'Past Volunteer',
  'Event Attendee',
  'Volunteer Call Attendee',
  'Signed Nomination Paper',
  'Collected Papers Before',
  'Community First Party Interest',
  'Jon Kiper Supporter',
  'Warm Personal Contact',
  'Org Contact',
  'Media / Influencer Contact',
  'Potential Host',
  'Potential Volunteer Captain',
] as const
